/*
 * Risk scoring API
 *
 * This is an API that provides whitebox risk scoring
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package risk_scoring

// Risk offsets
type Offsets struct {
	CombinedRiskOffset float32 `json:"combinedRiskOffset"`
	FraudRiskOffset float32 `json:"fraudRiskOffset"`
	LendingRiskOffset float32 `json:"lendingRiskOffset"`
	ReputationRiskOffset float32 `json:"reputationRiskOffset"`
}
