/*
 * Risk scoring API
 *
 * This is an API that provides whitebox risk scoring
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package risk_scoring

// Unstructured JSON risk elaboration
type RiskElaboration struct {
}
