/*
 * Risk scoring API
 *
 * This is an API that provides whitebox risk scoring
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package risk_scoring

// Risk score
type RiskScores struct {
	CombinedRisk float32 `json:"combinedRisk"`
	FraudRisk float32 `json:"fraudRisk"`
	LendingRisk float32 `json:"lendingRisk"`
	ReputationRisk float32 `json:"reputationRisk"`
}
