/*
 * Risk scoring API
 *
 * This is an API that provides whitebox risk scoring
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Risk score response
type RiskReport struct {
	Reasons []Reason `json:"reasons"`
	RiskScores *RiskScores `json:"riskScores"`
}
